### PR TITLE
Update physics

### LINKED ISSUE #4: Upstream doesn't support pygame 2
This currently prevents this application to be ported to a newer GNOME runtimes.

See https://github.com/sugarlabs/physics/issues/50

### PR DESCRIPTION
**Pull request by sparshg**
Closes #4

### CODE REVIEW

**Comment by sparshg** [comment]
Data checker on activity can be added after https://github.com/sugarlabs/physics/pull/58

**Comment by sparshg** [comment]
Added patch to fix samples, also re-added sample 1

**Review by tchx84 — CHANGES_REQUESTED** [review]
Seems to work fine :+1: , but there's a few errors I noticed, e.g.

```
Traceback (most recent call last):
  File "/app/share/sugar/activities/Physics.activity/sugargame/event.py", line 150, in _keydown_cb
    return self._keyevent(widget, event, pygame.KEYDOWN)
  File "/app/share/sugar/activities/Physics.activity/sugargame/event.py", line 191, in _keyevent
    mod = self._keymods()
  File "/app/share/sugar/activities/Physics.activity/sugargame/event.py", line 167, in _keymods
    mod |= self.__keystate[key_val] and mod_val
IndexError: list index out of range
```

To reproduce:

1. `rm -rf /var/home/tchx84/.var/app/org.sugarlabs.Physics/`
2. `flatpak run org.sugarlabs.Physics`
3. Close the shape-selection palette.

**Comment by sparshg** [comment]
That is an issue regarding sugargame being outdated, you can press any key and it will show this error, because pygame 2 has updated the keycodes for those in `mod_map` in `event.py`, hence index out of range issue.

```
>>> pg.K_LALT
1073742050
>>> hex(pg.K_LALT)
'0x400000e2'
```

This should be fixed in the sugargame repo instead since its not blocking issue for physics? so that other activities can also include the fix for this.

**Comment by sparshg** [comment]
Fixes have been merged in upstream, I will create data checker for activity once version is updated

**Comment by sparshg** [comment]
Patched sugargame

**Comment by sparshg** [comment]
Opened PR in sugargame upstream too, https://github.com/sugarlabs/sugargame/pull/15

**Comment by sparshg** [comment]
> Opened PR in sugargame upstream too

This has been merged.

**Review by tchx84 — CHANGES_REQUESTED** [review]
@sparshg I have been testing this a bit more thoroughly, and notice the following:

1. Open the Physics and reset the canvas, to start clean.
2. Go to the "play" toolbar and stop all movement.
3. Go to the "draw" toolbar, add a few floating shapes, and try the different "pins" on these shapes (for rotating it, etc)

I noticed this a couple times, but after the third or fourth shape with pins, the pygame canvas would start freezing, to the point where not even the cursor is moving.

**Comment by tchx84** [comment]
> @sparshg I have been testing this a bit more thoroughly, and notice the following:
> 
> 1. Open the Physics and reset the canvas, to start clean.
> 2. Go to the "play" toolbar and stop all movement.
> 3. Go to the "draw" toolbar, add a few floating shapes, and try the different "pins" on these shapes (for rotating it, etc)
> 
> I noticed this a couple times, but after the third or fourth shape with pins, the pygame canvas would start freezing, to the point where not even the cursor is moving.

I also noticed some strange random behaviors, like sometimes the pins won't pin the object, and when movement is resumed these will simply fall down to the "ground", instead of being pinned and rotate.

**Comment by sparshg** [comment]
This has been a known bug for a long time now: https://github.com/sugarlabs/physics/issues/27

I had tried looking into the issue but couldn't find whats wrong, I will try to dig a bit more on this.

**Comment by tchx84** [comment]
> @sparshg I have been testing this a bit more thoroughly, and notice the following:
> 
> 1. Open the Physics and reset the canvas, to start clean.
> 2. Go to the "play" toolbar and stop all movement.
> 3. Go to the "draw" toolbar, add a few floating shapes, and try the different "pins" on these shapes (for rotating it, etc)
> 
> I noticed this a couple times, but after the third or fourth shape with pins, the pygame canvas would start freezing, to the point where not even the cursor is moving.

@sparshg this one seems more critical..

**Comment by sparshg** [comment]
I tried this, the objects do fall to ground or glitch out and go crazy occasionally with pins, but I didn't experience any crashes. This is what I tried:

https://github.com/flathub/org.sugarlabs.Physics/assets/43041139/71b7cd6b-20b4-40a3-a7a6-15a52481bef1

I tried this on Ubuntu LTS 22.04, should I try to install it on some other distro?

**Comment by tchx84** [comment]
> @sparshg I have been testing this a bit more thoroughly, and notice the following:
> 
> 1. Open the Physics and reset the canvas, to start clean.
> 2. Go to the "play" toolbar and stop all movement.
> 3. Go to the "draw" toolbar, add a few floating shapes, and try the different "pins" on these shapes (for rotating it, etc)
> 
> I noticed this a couple times, but after the third or fourth shape with pins, the pygame canvas would start freezing, to the point where not even the cursor is moving.

What I am describing here is this:

[Screencast from 2023-08-25 16-25-23.webm](https://github.com/flathub/org.sugarlabs.Physics/assets/481418/c3e5282c-ce05-4182-9d43-3024b5e8ef1a)

Note how when I am about to add "rotating motor" pin to the third shape, the whole canvas freezes. I can still interact with the GTK side of things, but the pygame side is completely frozen.

I get this error, which might or not be related

```
Traceback (most recent call last):
  File "/app/share/sugar/activities/Physics.activity/physics.py", line 155, in run
    self.currentTool.handleEvents(event)
  File "/app/share/sugar/activities/Physics.activity/tools.py", line 122, in handleEvents
    return self.handleToolEvent(event)
  File "/app/share/sugar/activities/Physics.activity/tools.py", line 811, in handleToolEvent
    self.constructor(self.jb1pos, self.palette_data['speed'])
  File "/app/share/sugar/activities/Physics.activity/tools.py", line 816, in constructor
    self.game.world.add.motor(body, pos, speed=speed)
  File "/app/share/sugar/activities/Physics.activity/myelements/add_objects.py", line 585, in motor
    self.parent.world.CreateJoint(jointDef)
  File "/app/lib/python3.10/site-packages/Box2D/Box2D.py", line 3354, in CreateJoint
    return self.__CreateJoint(defn)
AssertionError: def->bodyA != def->bodyB
```

@sparshg focus on this.

**Comment by sparshg** [comment]
Yep, I am able to reproduce this issue now, working on it.

**Comment by sparshg** [comment]
Upstream fix https://github.com/sugarlabs/physics/pull/59
This also fixes the motor not getting pinned and objects glitching out, etc.

Deleted fix-load patch since the fix was merged in upstream

**Comment by tchx84** [comment]
> Upstream fix [sugarlabs/physics#59](https://github.com/sugarlabs/physics/pull/59) This also fixes the motor not getting pinned and objects glitching out, etc.
> 
> Deleted fix-load patch since the fix was merged in upstream

Excellent.

**Review by tchx84 — APPROVED** [review]

**Pull request merged**
